### ISSUE TITLE
Who made that docker on god

### ISSUE THREAD

**Issue by zzupart** [farneser/tg-bio-time-bot#1]
Bro i was trying to build this project the whole DAY and i just threw it all away and rewrote it and it is working finally!!!!!!!!!! how were you able to write such a bad dockerfile i feel bad for you

**Comment by farneser** [comment]
What problems did you encounter, in the instructions are just commands that must be entered one by one to run, there you have to login to your tg account, so this is the solution.

Session is thrown through volum to not build again if you are logged out or something like that.

What exactly is wrong with dockerfile

**Comment by zzupart** [comment]
i cant tell but the thing that it creates a directory bio.session when a file bio.session is needed is creating conflicts and is wrong in so many ways. sorry for agressive issue but bro i was so frustrated. thanks for writing this script tho, i just think that docker is unnecesarry in so small projects

**Comment by zzupart** [comment]
and yup volum must be a directory, not a file

**Comment by farneser** [comment]
Docker is used here to make starting and stopping as easy as possible

> i cant tell but the thing that it creates a directory bio.session when a file bio.session is needed is creating conflicts and is wrong in so many ways. sorry for agressive issue but bro i was so frustrated. thanks for writing this script tho, i just think that docker is unnecesarry in so small projects

**Comment by farneser** [comment]
in [last commit](https://github.com/farneser/tg-bio-time-bot/commit/86887e0062f42bcfeba14c6bc7839743d0d86107) i move session file to session folder and now docker do not create folder instead file 

> and yup volum must be a directory, not a file
